# Generated by Django 5.1.7 on 2025-04-21 15:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming ')], max_length=2, verbose_name='State')),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Enter a valid 5-digit ZIP code')], verbose_name='ZIP Code')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Enter a valid 10-digit phone number')], verbose_name='Phone Number')),
                ('fax', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Enter a valid 10-digit fax number')], verbose_name='Fax Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='DefaultDrawerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('surcharge_width', models.DecimalField(decimal_places=2, default=0.0, help_text='Width surcharge for drawer pricing', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('surcharge_depth', models.DecimalField(decimal_places=2, default=0.0, help_text='Depth surcharge for drawer pricing', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('surcharge_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage surcharge for drawer pricing', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('finish_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional charge for finishing', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('undermount_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional charge for undermount slides', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ends_cutting_adjustment', models.DecimalField(decimal_places=3, default=0.0, help_text='Adjustment for cutting drawer ends', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('sides_cutting_adjustment', models.DecimalField(decimal_places=3, default=0.0, help_text='Adjustment for cutting drawer sides', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('plywood_size_adjustment', models.DecimalField(decimal_places=3, default=0.0, help_text='Adjustment for plywood sizing', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
            ],
            options={
                'verbose_name': 'Default Drawer Settings',
                'verbose_name_plural': 'Default Drawer Settings',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('arch', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrawerBottomSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('thickness', models.DecimalField(decimal_places=3, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': 'Drawer Bottom Type',
                'verbose_name_plural': 'Drawer Bottom Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrawerEdgeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Drawer Edge Type',
                'verbose_name_plural': 'Drawer Edge Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrawerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=50.0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('height', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': 'Drawer Pricing',
                'verbose_name_plural': 'Drawer Pricing',
            },
        ),
        migrations.CreateModel(
            name='DrawerWoodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': 'Drawer Wood Stock',
                'verbose_name_plural': 'Drawer Wood Stocks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EdgeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PanelRise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PanelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('surcharge_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('surcharge_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('surcharge_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum_sq_ft', models.DecimalField(decimal_places=2, max_digits=5)),
                ('use_flat_panel_price', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RailDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('top', models.DecimalField(decimal_places=3, help_text='Default top rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('bottom', models.DecimalField(decimal_places=3, help_text='Default bottom rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('left', models.DecimalField(decimal_places=3, help_text='Default left rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('right', models.DecimalField(decimal_places=3, help_text='Default right rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
            ],
            options={
                'verbose_name': 'Rail Defaults',
                'verbose_name_plural': 'Rail Defaults',
            },
        ),
        migrations.CreateModel(
            name='WoodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('raised_panel_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flat_panel_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENT', max_length=10, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount Value')),
                ('surcharge_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENT', max_length=10, verbose_name='Surcharge Type')),
                ('surcharge_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Surcharge Value')),
                ('shipping_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENT', max_length=10, verbose_name='Shipping Type')),
                ('shipping_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping Value')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defaults', to='core.customer')),
            ],
            options={
                'verbose_name': 'Customer Default',
                'verbose_name_plural': 'Customer Defaults',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_quote', models.BooleanField(default=False, verbose_name='Is Quote')),
                ('billing_address1', models.CharField(max_length=255, verbose_name='Billing Address Line 1')),
                ('billing_address2', models.CharField(blank=True, max_length=255, verbose_name='Billing Address Line 2')),
                ('order_date', models.DateField(verbose_name='Order Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount Amount')),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Surcharge Amount')),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax Amount')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='GenericLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('door', 'Door'), ('drawer', 'Drawer'), ('other', 'Other')], default='other', max_length=10, verbose_name='Item Type')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price per Unit')),
                ('custom_price', models.BooleanField(default=False, help_text='Indicates if the price has been manually adjusted', verbose_name='Custom Price')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('name', models.CharField(help_text='Description of the item or service', max_length=255, verbose_name='Item Name')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_items', to='core.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Miscellaneous Item',
                'verbose_name_plural': 'Miscellaneous Items',
            },
        ),
        migrations.CreateModel(
            name='DrawerLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('door', 'Door'), ('drawer', 'Drawer'), ('other', 'Other')], default='other', max_length=10, verbose_name='Item Type')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price per Unit')),
                ('custom_price', models.BooleanField(default=False, help_text='Indicates if the price has been manually adjusted', verbose_name='Custom Price')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in inches', max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in inches', max_digits=6)),
                ('depth', models.DecimalField(decimal_places=2, help_text='Depth in inches', max_digits=6)),
                ('undermount', models.BooleanField(default=False, help_text='Whether drawer uses undermount slides')),
                ('finishing', models.BooleanField(default=False, help_text='Whether drawer requires finishing')),
                ('bottom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drawer_items', to='core.drawerbottomsize')),
                ('edge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drawer_items', to='core.draweredgetype')),
                ('wood_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drawer_items', to='core.drawerwoodstock')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawer_items', to='core.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Drawer',
                'verbose_name_plural': 'Drawers',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('panels_across', models.PositiveSmallIntegerField(default=1)),
                ('panels_down', models.PositiveSmallIntegerField(default=1)),
                ('panel_overlap', models.DecimalField(decimal_places=3, max_digits=5)),
                ('designs_on_top', models.BooleanField(default=False)),
                ('designs_on_bottom', models.BooleanField(default=False)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.design')),
                ('panel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paneltype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoorLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('door', 'Door'), ('drawer', 'Drawer'), ('other', 'Other')], default='other', max_length=10, verbose_name='Item Type')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price per Unit')),
                ('custom_price', models.BooleanField(default=False, help_text='Indicates if the price has been manually adjusted', verbose_name='Custom Price')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in inches', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in inches', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rail_top', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Top rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('rail_bottom', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Bottom rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('rail_left', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Left rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('rail_right', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Right rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('edge_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.edgeprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_items', to='core.order', verbose_name='Order')),
                ('panel_rise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.panelrise')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.style')),
                ('wood_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.woodstock')),
            ],
            options={
                'verbose_name': 'Door Item',
                'verbose_name_plural': 'Door Items',
            },
        ),
    ]
