# Generated by Django 5.1.7 on 2025-04-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='door_defaults',
            field=models.JSONField(blank=True, default=dict, help_text='Door default preferences for this customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='drawer_defaults',
            field=models.JSONField(blank=True, default=dict, help_text='Drawer default preferences for this customer'),
        ),
    ]
