# Generated by Django 5.1.7 on 2025-04-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_load_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doorlineitem',
            name='design',
        ),
        migrations.RemoveField(
            model_name='doorlineitem',
            name='panel_type',
        ),
    ]
