# Generated by Django 5.1.7 on 2025-04-22 22:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_door_defaults_customer_drawer_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorlineitem',
            name='interior_rail_size',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Interior rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AddField(
            model_name='raildefaults',
            name='interior_rail_size',
            field=models.DecimalField(decimal_places=3, default=2.25, help_text='Default interior rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
            preserve_default=False,
        ),
    ]
