# Generated by Django 5.1.7 on 2025-04-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doorlineitem_interior_rail_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='taxable',
            field=models.BooleanField(default=False, help_text='Whether this customer should be charged tax on orders', verbose_name='Taxable'),
        ),
    ]
