# Generated by Django 5.1.7 on 2025-04-23 20:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_taxable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscellaneousDoorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_height', models.DecimalField(decimal_places=3, help_text='Extra height to add when gluing sheet', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('extra_width', models.DecimalField(decimal_places=3, help_text='Extra width to add when gluing sheet', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('glue_min_width', models.DecimalField(decimal_places=3, help_text='Minimum width for gluing sheet', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('rail_extra', models.DecimalField(decimal_places=3, help_text='Rail joint extra', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('drawer_front', models.ForeignKey(help_text='Panel type to use for drawer fronts', on_delete=django.db.models.deletion.PROTECT, related_name='drawer_front_settings', to='core.paneltype')),
                ('drawer_slab', models.ForeignKey(help_text='Panel type to use for drawer slabs', on_delete=django.db.models.deletion.PROTECT, related_name='drawer_slab_settings', to='core.paneltype')),
            ],
            options={
                'verbose_name': 'Miscellaneous Door Settings',
                'verbose_name_plural': 'Miscellaneous Door Settings',
            },
        ),
    ]
