# Generated by Django 5.1.7 on 2025-04-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_miscellaneousdoorsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorlineitem',
            name='sand_cross_grain',
            field=models.BooleanField(default=False, help_text='Whether to sand across the grain'),
        ),
        migrations.AddField(
            model_name='doorlineitem',
            name='sand_edge',
            field=models.BooleanField(default=False, help_text='Whether to sand the edges of the door'),
        ),
    ]
