# Generated by Django 5.1.7 on 2025-04-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_discount_amount_order_shipping_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
