# Generated by Django 5.1.7 on 2025-04-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorlineitem',
            name='type',
            field=models.CharField(choices=[('door', 'Door'), ('drawer', 'Drawer'), ('other', 'Other')], default='other', max_length=10, verbose_name='Item Type'),
        ),
    ]
