# Generated by Django 5.1.7 on 2025-04-11 16:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_doorlineitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('top', models.DecimalField(decimal_places=2, help_text='Default top rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('bottom', models.DecimalField(decimal_places=2, help_text='Default bottom rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('left', models.DecimalField(decimal_places=2, help_text='Default left rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('right', models.DecimalField(decimal_places=2, help_text='Default right rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': 'Rail Defaults',
                'verbose_name_plural': 'Rail Defaults',
            },
        ),
    ]
