# Generated by Django 5.1.7 on 2025-04-14 06:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_doorlineitem_rail_bottom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorlineitem',
            name='rail_bottom',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Bottom rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='doorlineitem',
            name='rail_left',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Left rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='doorlineitem',
            name='rail_right',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Right rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='doorlineitem',
            name='rail_top',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Top rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
