# Generated by Django 5.1.7 on 2025-04-14 22:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_doorlineitem_rail_bottom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawerBottomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Drawer Bottom Type',
                'verbose_name_plural': 'Drawer Bottom Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrawerEdgeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Drawer Edge Type',
                'verbose_name_plural': 'Drawer Edge Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrawerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('depth_price_factor', models.DecimalField(decimal_places=2, default=1.0, help_text='Price multiplier per inch of depth', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('undermount_price_addition', models.DecimalField(decimal_places=2, default=20.0, help_text='Additional price for undermount slides', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('finishing_price_factor', models.DecimalField(decimal_places=2, default=1.25, help_text='Price multiplier for finished drawers', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': 'Drawer Pricing',
                'verbose_name_plural': 'Drawer Pricing',
            },
        ),
        migrations.CreateModel(
            name='DrawerWoodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Drawer Wood Stock',
                'verbose_name_plural': 'Drawer Wood Stocks',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='doorlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_items', to='core.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='raildefaults',
            name='bottom',
            field=models.DecimalField(decimal_places=3, help_text='Default bottom rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='raildefaults',
            name='left',
            field=models.DecimalField(decimal_places=3, help_text='Default left rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='raildefaults',
            name='right',
            field=models.DecimalField(decimal_places=3, help_text='Default right rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='raildefaults',
            name='top',
            field=models.DecimalField(decimal_places=3, help_text='Default top rail size in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.CreateModel(
            name='DrawerLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('door', 'Door'), ('drawer', 'Drawer'), ('other', 'Other')], default='other', max_length=10, verbose_name='Item Type')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price per Unit')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in inches', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('4.00')), django.core.validators.MaxValueValidator(Decimal('60.00'))])),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in inches', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('2.00')), django.core.validators.MaxValueValidator(Decimal('24.00'))])),
                ('depth', models.DecimalField(decimal_places=2, help_text='Depth in inches', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('4.00')), django.core.validators.MaxValueValidator(Decimal('36.00'))])),
                ('undermount', models.BooleanField(default=False, help_text='Whether drawer uses undermount slides')),
                ('finishing', models.BooleanField(default=False, help_text='Whether drawer requires finishing')),
                ('custom_price', models.BooleanField(default=False, help_text='Whether the price is manually set')),
                ('notes', models.TextField(blank=True)),
                ('bottom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drawer_items', to='core.drawerbottomtype')),
                ('edge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drawer_items', to='core.draweredgetype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawer_items', to='core.order', verbose_name='Order')),
                ('wood_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drawer_items', to='core.drawerwoodstock')),
            ],
            options={
                'verbose_name': 'Drawer',
                'verbose_name_plural': 'Drawers',
            },
        ),
    ]
