# Generated by Django 5.1.7 on 2025-04-14 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_drawerbottomtype_draweredgetype_drawerpricing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawerlineitem',
            name='bottom',
        ),
        migrations.RemoveField(
            model_name='drawerlineitem',
            name='edge_type',
        ),
        migrations.RemoveField(
            model_name='drawerlineitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='drawerlineitem',
            name='wood_stock',
        ),
        migrations.DeleteModel(
            name='DrawerPricing',
        ),
        migrations.AlterField(
            model_name='doorlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.order', verbose_name='Order'),
        ),
        migrations.DeleteModel(
            name='DrawerBottomType',
        ),
        migrations.DeleteModel(
            name='DrawerEdgeType',
        ),
        migrations.DeleteModel(
            name='DrawerLineItem',
        ),
        migrations.DeleteModel(
            name='DrawerWoodStock',
        ),
    ]
