# Generated by Django 5.1.7 on 2025-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_drawerbottomsize_draweredgetype_drawerpricing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawerlineitem',
            name='depth',
            field=models.DecimalField(decimal_places=2, help_text='Depth in inches', max_digits=6),
        ),
        migrations.AlterField(
            model_name='drawerlineitem',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Height in inches', max_digits=6),
        ),
        migrations.AlterField(
            model_name='drawerlineitem',
            name='width',
            field=models.DecimalField(decimal_places=2, help_text='Width in inches', max_digits=6),
        ),
    ]
