# Generated by Django 5.1.7 on 2025-04-15 18:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_drawerlineitem_depth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('door', 'Door'), ('drawer', 'Drawer'), ('other', 'Other')], default='other', max_length=10, verbose_name='Item Type')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price per Unit')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('name', models.CharField(help_text='Description of the item or service', max_length=255, verbose_name='Item Name')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_items', to='core.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Miscellaneous Item',
                'verbose_name_plural': 'Miscellaneous Items',
            },
        ),
    ]
