# Generated by Django 5.1.7 on 2025-04-15 21:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_genericlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorlineitem',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Manually override the calculated price for this item.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Custom Price'),
        ),
        migrations.AddField(
            model_name='drawerlineitem',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Manually override the calculated price for this item.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Custom Price'),
        ),
        migrations.AddField(
            model_name='genericlineitem',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Manually override the calculated price for this item.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Custom Price'),
        ),
    ]
