# Generated by Django 5.1.7 on 2025-04-16 15:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_doorlineitem_custom_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultDrawerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('surcharge_width', models.DecimalField(decimal_places=2, default=0.0, help_text='Width surcharge for drawer pricing', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('surcharge_depth', models.DecimalField(decimal_places=2, default=0.0, help_text='Depth surcharge for drawer pricing', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('surcharge_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage surcharge for drawer pricing', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('finish_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional charge for finishing', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('undermount_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional charge for undermount slides', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ends_cutting_adjustment', models.DecimalField(decimal_places=3, default=0.0, help_text='Adjustment for cutting drawer ends', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('sides_cutting_adjustment', models.DecimalField(decimal_places=3, default=0.0, help_text='Adjustment for cutting drawer sides', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('plywood_size_adjustment', models.DecimalField(decimal_places=3, default=0.0, help_text='Adjustment for plywood sizing', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
            ],
            options={
                'verbose_name': 'Default Drawer Settings',
                'verbose_name_plural': 'Default Drawer Settings',
            },
        ),
        migrations.AlterField(
            model_name='doorlineitem',
            name='custom_price',
            field=models.BooleanField(default=False, help_text='Indicates if the price has been manually adjusted', verbose_name='Custom Price'),
        ),
        migrations.AlterField(
            model_name='drawerlineitem',
            name='custom_price',
            field=models.BooleanField(default=False, help_text='Indicates if the price has been manually adjusted', verbose_name='Custom Price'),
        ),
        migrations.AlterField(
            model_name='genericlineitem',
            name='custom_price',
            field=models.BooleanField(default=False, help_text='Indicates if the price has been manually adjusted', verbose_name='Custom Price'),
        ),
    ]
